window.esdocSearchIndex = [
  [
    "speechyl/src/speechyl.es6.js~speechyl",
    "class/src/speechYL.es6.js~SpeechYL.html",
    "<span>SpeechYL</span> <span class=\"search-result-import-path\">speechyl/src/speechYL.es6.js</span>",
    "class"
  ],
  [
    "speechyl/src/example/dataobjects.js~func",
    "variable/index.html#static-variable-func",
    "<span>func</span> <span class=\"search-result-import-path\">speechyl/src/example/dataObjects.js</span>",
    "variable"
  ],
  [
    "speechyl/src/example/dataobjects.js~recognitionobj",
    "variable/index.html#static-variable-recognitionObj",
    "<span>recognitionObj</span> <span class=\"search-result-import-path\">speechyl/src/example/dataObjects.js</span>",
    "variable"
  ],
  [
    "speechyl/src/example/dataobjects.js~simpledata2",
    "variable/index.html#static-variable-simpleData2",
    "<span>simpleData2</span> <span class=\"search-result-import-path\">speechyl/src/example/dataObjects.js</span>",
    "variable"
  ],
  [
    "speechyl/src/example/dataobjects.js~simpledata",
    "variable/index.html#static-variable-simpleData",
    "<span>simpleData</span> <span class=\"search-result-import-path\">speechyl/src/example/dataObjects.js</span>",
    "variable"
  ],
  [
    "speechyl/src/example/dataobjects.js~synthesisobj",
    "variable/index.html#static-variable-synthesisObj",
    "<span>synthesisObj</span> <span class=\"search-result-import-path\">speechyl/src/example/dataObjects.js</span>",
    "variable"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/example/dataobjects.js",
    "file/src/example/dataObjects.js.html",
    "src/example/dataObjects.js",
    "file"
  ],
  [
    "src/speechyl.es6.js",
    "file/src/speechYL.es6.js.html",
    "src/speechYL.es6.js",
    "file"
  ],
  [
    "src/speechyl.es6.js~speechyl#actiondata",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-method-actionData",
    "src/speechYL.es6.js~SpeechYL#actionData",
    "method"
  ],
  [
    "src/speechyl.es6.js~speechyl#actiondatainclude",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-method-actionDataInclude",
    "src/speechYL.es6.js~SpeechYL#actionDataInclude",
    "method"
  ],
  [
    "src/speechyl.es6.js~speechyl#actiondatastart",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-method-actionDataStart",
    "src/speechYL.es6.js~SpeechYL#actionDataStart",
    "method"
  ],
  [
    "src/speechyl.es6.js~speechyl#actiondatatype",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-method-actionDataType",
    "src/speechYL.es6.js~SpeechYL#actionDataType",
    "method"
  ],
  [
    "src/speechyl.es6.js~speechyl#addcommand",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-method-addCommand",
    "src/speechYL.es6.js~SpeechYL#addCommand",
    "method"
  ],
  [
    "src/speechyl.es6.js~speechyl#commands",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-member-commands",
    "src/speechYL.es6.js~SpeechYL#commands",
    "member"
  ],
  [
    "src/speechyl.es6.js~speechyl#commandsfunc",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-member-commandsFunc",
    "src/speechYL.es6.js~SpeechYL#commandsFunc",
    "member"
  ],
  [
    "src/speechyl.es6.js~speechyl#constructor",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-constructor-constructor",
    "src/speechYL.es6.js~SpeechYL#constructor",
    "method"
  ],
  [
    "src/speechyl.es6.js~speechyl#createcommands",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-method-createCommands",
    "src/speechYL.es6.js~SpeechYL#createCommands",
    "method"
  ],
  [
    "src/speechyl.es6.js~speechyl#getvoicebyname",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-method-getVoiceByName",
    "src/speechYL.es6.js~SpeechYL#getVoiceByName",
    "method"
  ],
  [
    "src/speechyl.es6.js~speechyl#getvoicesbylang",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-method-getVoicesByLang",
    "src/speechYL.es6.js~SpeechYL#getVoicesByLang",
    "method"
  ],
  [
    "src/speechyl.es6.js~speechyl#issentencesaid",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-method-isSentenceSaid",
    "src/speechYL.es6.js~SpeechYL#isSentenceSaid",
    "method"
  ],
  [
    "src/speechyl.es6.js~speechyl#iswordsaid",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-method-isWordSaid",
    "src/speechYL.es6.js~SpeechYL#isWordSaid",
    "method"
  ],
  [
    "src/speechyl.es6.js~speechyl#lasttranscript",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-member-lastTranscript",
    "src/speechYL.es6.js~SpeechYL#lastTranscript",
    "member"
  ],
  [
    "src/speechyl.es6.js~speechyl#launchfunc",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-method-launchFunc",
    "src/speechYL.es6.js~SpeechYL#launchFunc",
    "method"
  ],
  [
    "src/speechyl.es6.js~speechyl#loadjsoncommands",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-method-loadJsonCommands",
    "src/speechYL.es6.js~SpeechYL#loadJsonCommands",
    "method"
  ],
  [
    "src/speechyl.es6.js~speechyl#maxalternatives",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-set-maxAlternatives",
    "src/speechYL.es6.js~SpeechYL#maxAlternatives",
    "member"
  ],
  [
    "src/speechyl.es6.js~speechyl#onaudioend",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-set-onaudioend",
    "src/speechYL.es6.js~SpeechYL#onaudioend",
    "member"
  ],
  [
    "src/speechyl.es6.js~speechyl#onaudiostart",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-set-onaudiostart",
    "src/speechYL.es6.js~SpeechYL#onaudiostart",
    "member"
  ],
  [
    "src/speechyl.es6.js~speechyl#onend",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-set-onend",
    "src/speechYL.es6.js~SpeechYL#onend",
    "member"
  ],
  [
    "src/speechyl.es6.js~speechyl#onerror",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-set-onerror",
    "src/speechYL.es6.js~SpeechYL#onerror",
    "member"
  ],
  [
    "src/speechyl.es6.js~speechyl#onnomatch",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-set-onnomatch",
    "src/speechYL.es6.js~SpeechYL#onnomatch",
    "member"
  ],
  [
    "src/speechyl.es6.js~speechyl#onresult",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-set-onresult",
    "src/speechYL.es6.js~SpeechYL#onresult",
    "member"
  ],
  [
    "src/speechyl.es6.js~speechyl#onsoundend",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-set-onsoundend",
    "src/speechYL.es6.js~SpeechYL#onsoundend",
    "member"
  ],
  [
    "src/speechyl.es6.js~speechyl#onsoundstart",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-set-onsoundstart",
    "src/speechYL.es6.js~SpeechYL#onsoundstart",
    "member"
  ],
  [
    "src/speechyl.es6.js~speechyl#onspeechend",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-set-onspeechend",
    "src/speechYL.es6.js~SpeechYL#onspeechend",
    "member"
  ],
  [
    "src/speechyl.es6.js~speechyl#onspeechstart",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-set-onspeechstart",
    "src/speechYL.es6.js~SpeechYL#onspeechstart",
    "member"
  ],
  [
    "src/speechyl.es6.js~speechyl#onstart",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-set-onstart",
    "src/speechYL.es6.js~SpeechYL#onstart",
    "member"
  ],
  [
    "src/speechyl.es6.js~speechyl#onvoiceschanged",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-set-onvoiceschanged",
    "src/speechYL.es6.js~SpeechYL#onvoiceschanged",
    "member"
  ],
  [
    "src/speechyl.es6.js~speechyl#recogabort",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-method-recogAbort",
    "src/speechYL.es6.js~SpeechYL#recogAbort",
    "method"
  ],
  [
    "src/speechyl.es6.js~speechyl#recogstart",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-method-recogStart",
    "src/speechYL.es6.js~SpeechYL#recogStart",
    "method"
  ],
  [
    "src/speechyl.es6.js~speechyl#recogstop",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-method-recogStop",
    "src/speechYL.es6.js~SpeechYL#recogStop",
    "method"
  ],
  [
    "src/speechyl.es6.js~speechyl#recognition",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-member-recognition",
    "src/speechYL.es6.js~SpeechYL#recognition",
    "member"
  ],
  [
    "src/speechyl.es6.js~speechyl#recognitionlang",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-set-recognitionLang",
    "src/speechYL.es6.js~SpeechYL#recognitionLang",
    "member"
  ],
  [
    "src/speechyl.es6.js~speechyl#say",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-method-say",
    "src/speechYL.es6.js~SpeechYL#say",
    "method"
  ],
  [
    "src/speechyl.es6.js~speechyl#saysentenceafterrecognition",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-method-saySentenceAfterRecognition",
    "src/speechYL.es6.js~SpeechYL#saySentenceAfterRecognition",
    "method"
  ],
  [
    "src/speechyl.es6.js~speechyl#saysentencefromdata",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-method-saySentenceFromData",
    "src/speechYL.es6.js~SpeechYL#saySentenceFromData",
    "method"
  ],
  [
    "src/speechyl.es6.js~speechyl#serviceuri",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-set-serviceURI",
    "src/speechYL.es6.js~SpeechYL#serviceURI",
    "member"
  ],
  [
    "src/speechyl.es6.js~speechyl#setlang",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-method-setLang",
    "src/speechYL.es6.js~SpeechYL#setLang",
    "method"
  ],
  [
    "src/speechyl.es6.js~speechyl#speak",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-method-speak",
    "src/speechYL.es6.js~SpeechYL#speak",
    "method"
  ],
  [
    "src/speechyl.es6.js~speechyl#synthcancel",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-method-synthCancel",
    "src/speechYL.es6.js~SpeechYL#synthCancel",
    "method"
  ],
  [
    "src/speechyl.es6.js~speechyl#synthpause",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-method-synthPause",
    "src/speechYL.es6.js~SpeechYL#synthPause",
    "method"
  ],
  [
    "src/speechyl.es6.js~speechyl#synthresume",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-method-synthResume",
    "src/speechYL.es6.js~SpeechYL#synthResume",
    "method"
  ],
  [
    "src/speechyl.es6.js~speechyl#synthtext",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-member-synthText",
    "src/speechYL.es6.js~SpeechYL#synthText",
    "member"
  ],
  [
    "src/speechyl.es6.js~speechyl#synthesis",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-member-synthesis",
    "src/speechYL.es6.js~SpeechYL#synthesis",
    "member"
  ],
  [
    "src/speechyl.es6.js~speechyl#synthesislang",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-set-synthesisLang",
    "src/speechYL.es6.js~SpeechYL#synthesisLang",
    "member"
  ],
  [
    "src/speechyl.es6.js~speechyl#utterance",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-member-utterance",
    "src/speechYL.es6.js~SpeechYL#utterance",
    "member"
  ],
  [
    "src/speechyl.es6.js~speechyl#voice",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-set-voice",
    "src/speechYL.es6.js~SpeechYL#voice",
    "member"
  ],
  [
    "src/speechyl.es6.js~speechyl#voices",
    "class/src/speechYL.es6.js~SpeechYL.html#instance-member-voices",
    "src/speechYL.es6.js~SpeechYL#voices",
    "member"
  ]
]